# -*- coding: utf-8 -*-
"""CleanData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXBvyOEV8_UlIPqlI0kkimXgx-vRHxxK
"""

import skimage.io as io
import skimage.filters as filters
import skimage.segmentation as segmentation
import skimage.measure as measure
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import zipfile

import kagglehub

# Download latest version
path = kagglehub.dataset_download("iarunava/cell-images-for-detecting-malaria")

print("Path to dataset files:", path)

"""**Basically i just tried to save the relavent features to two csv files so that it is more usable. Right now I was only able to extract the texture features and color features for large data set that was like 13k files**

**Test to see if the processing worked:**
"""

import cv2
import os
import numpy as np
import csv
from pathlib import Path

# Specify the path to the directory containing the images
dataset_path = Path(path)  # Replace with your actual path

# Function to extract mean and standard deviation of color channels
def extract_color_features(image):
    # Convert to RGB (if needed)
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    # Compute mean and standard deviation for each channel
    mean_r = np.mean(rgb_image[:, :, 0])
    mean_g = np.mean(rgb_image[:, :, 1])
    mean_b = np.mean(rgb_image[:, :, 2])
    std_r = np.std(rgb_image[:, :, 0])
    std_g = np.std(rgb_image[:, :, 1])
    std_b = np.std(rgb_image[:, :, 2])
    return [mean_r, mean_g, mean_b, std_r, std_g, std_b]

# Function to determine the label based on the file path
def get_label_from_path(file_name):
    if "Uninfected" in str(file_name):
        return "Uninfected"
    elif "Parasitized" in str(file_name):
        return "Parasitized"
    else:
        return "Unknown"

# Process images in the directory
color_features = []  # This will store features along with filenames and labels
for file_name in dataset_path.glob("**/*.*"):
    if file_name.suffix.lower() in {".png", ".jpg", ".jpeg"}:
        print(f"Processing {file_name}") # Properly join path using Pathlib
        image = cv2.imread(str(file_name))  # Ensure the path is a string for OpenCV
        if image is not None:
            # Extract color features and determine the label
            features = extract_color_features(image)
            label = get_label_from_path(file_name)
            color_features.append([file_name, label] + features)

# Write extracted features to a CSV file
csv_file_path = "color_features_with_labels.csv"
with open(csv_file_path, mode="w", newline="") as file:
    writer = csv.writer(file)
    # Header row
    writer.writerow(["Filename", "Label", "Mean_R", "Mean_G", "Mean_B", "Std_R", "Std_G", "Std_B"])
    for feature_set in color_features:
        # Write each image's filename, label, and features
        writer.writerow(feature_set)

# Example: Print extracted features for verification
for idx, feature_set in enumerate(color_features):
    print(f"Image {idx + 1} ({feature_set[0]}): Label: {feature_set[1]}, Features: {feature_set[2:]}")

"""Test to see if the processing worked"""

from google.colab import files
files.download('texture_features.csv')

from google.colab import files
files.download('color_features.csv')

import pandas as pd

# Upload your CSV file from the local system to Google Colab
from google.colab import files
uploaded = files.upload()

# Read the uploaded CSV file
df = pd.read_csv('color_features.csv')

# Function to update filenames in the CSV based on the file path
def update_csv_filenames(csv_data):
    # pull exactly “Uninfected” or “Parasitized” from the path
    csv_data['Updated_Filename'] = (
        csv_data['Filename']
        .str.extract(r'(Uninfected|Parasitized)', expand=False)
        # if you want to append “.png”:
        + '.png'
    )
    return csv_data

# Update the filenames in the CSV
df = update_csv_filenames(df)

# Save the cleaned CSV file within Colab
output_file = 'color_features_clean.csv'
df.to_csv(output_file, index=False)
print(f"Cleaned CSV file saved as {output_file}")

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import cv2
import numpy as np
import csv

def extract_texture(image):
    """
    Extract texture features using Local Binary Patterns (LBP).
    """
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    lbp = cv2.calcHist([gray_image], [0], None, [256], [0, 256])
    return lbp.flatten()

def process_images(directory):
    """
    Process all images in a directory and extract texture features.
    """
    texture_data = []

    # Iterate through all image files in the directory
    for filepath in directory.glob("**/*.*"):  # Recursively scans for all files
        if filepath.suffix.lower() in {".png", ".jpg", ".jpeg", ".bmp", ".tiff"}:
            print(f"Processing {filepath}")
            image = cv2.imread(str(filepath))  # Convert Path to string
            if image is not None:
                # Extract texture features
                texture = extract_texture(image)

                # Check if "Parasitized" or "Uninfected" is in the file path
                if "Parasitized" in str(filepath):
                    label = "Parasitized"
                elif "Uninfected" in str(filepath):
                    label = "Uninfected"
                else:
                    label = "Unknown"

                # Append the label and texture features
                texture_data.append((f"{label}_{filepath.name}", texture))

    return texture_data

# Define the directory using pathlib
data_dir = Path(path)

# Extract texture features from all images
texture_features = process_images(data_dir)

# Save the results to a CSV file
with open("texture_features.csv", mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Filename", "Texture Features"])
    for item in texture_features:
        writer.writerow([item[0], item[1].tolist()])

print("Texture analysis completed and saved to texture_features.csv!")

import cv2
import numpy as np
import csv
from pathlib import Path

def analyze_pixel_intensity(image_path):
    """
    Analyze and return pixel intensity statistics for an image.
    """
    image = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)  # Load in grayscale
    if image is not None:
        mean_intensity = np.mean(image)  # Compute mean pixel intensity
        variance_intensity = np.var(image)  # Compute variance of intensity
        return mean_intensity, variance_intensity
    return None, None

# Define the directory containing images
data_dir = Path(path)

# Initialize lists for storing results
results = []

# Process each image and call the analyze_pixel_intensity method
for filepath in data_dir.glob("**/*.*"):
    if filepath.suffix.lower() in {".png", ".jpg", ".jpeg", ".bmp", ".tiff"}:
        if "Uninfected" in str(filepath):
            label = "Uninfected"
        elif "Parasitized" in str(filepath):
            label = "Parasitized"
        else:
            label = "Unknown"

        # Call the analyze_pixel_intensity function here
        mean, var = analyze_pixel_intensity(filepath)
        if mean is not None and var is not None:
            results.append([filepath.name, label, mean, var])

# Save the results to a CSV file
output_file = "pixel_intensity_analysis.csv"
with open(output_file, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Filename", "Label", "Mean Intensity", "Variance Intensity"])
    writer.writerows(results)

print(f"Pixel intensity analysis completed and saved to {output_file}!")



"""**Renames files in the dataset to a more readable filename**"""

import csv
import os


def rename_image_entries_in_csv(csv_file_path, output_csv_file_path):
   """
   Renames images in a directory to a sequential format like Data1, Data2, etc.

   Args: dataset_path: The path to the directory containing the images.
   """
   image_count = 0  # Initialize counter for images
   rows = []


   # Open and read the CSV file
   with open(csv_file_path, mode="r") as file:
       reader = csv.DictReader(file)
       header = reader.fieldnames  # Get the column names
       for row in reader:
           # Check if the 'Filename' entry is an image path
           if row["Filename"].lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".tiff")):
               image_count += 1
               # Rename the image entry to Data1, Data2, etc.
               file_extension = os.path.splitext(row["Filename"])[1]  # Get the file extension
               new_filename = f"Data{image_count}{file_extension}"  # Create new filename
               row["Filename"] = new_filename  # Update the 'Filename' column
           rows.append(row)


   # Write the updated rows to a new CSV file
   with open(output_csv_file_path, mode="w", newline="") as file:
       writer = csv.DictWriter(file, fieldnames=header)
       writer.writeheader()  # Write the header row
       writer.writerows(rows)  # Write the updated rows


   print(f"Renamed {image_count} image entries in {csv_file_path} and saved to {output_csv_file_path}")

input_csv = "/content/drive/My Drive/texture_features_clean1.csv"
output_csv = "updated_texture_features_clean.csv"
rename_image_entries_in_csv(input_csv, output_csv)



from google.colab import files
files.download('updated_texture_features_clean.csv')

import pandas as pd

def process_csv(input_csv, output_csv):
    # Read the input CSV file into a DataFrame
    df = pd.read_csv(input_csv)

    # Check if the 'Filename' column exists
    if "Filename" not in df.columns:
        raise ValueError("Input CSV does not contain a 'Filename' column.")

    # Create a new column 'Label' based on keywords in the 'Filename' column
    df['Label'] = df['Filename'].apply(lambda x: "Uninfected" if "Uninfected" in x
                                       else "Parasitized" if "Parasitized" in x
                                       else "Unknown")

    # Rename the 'Filename' column entries to 'Data1', 'Data2', etc.
    df['Filename'] = ["Data" + str(i + 1) for i in range(len(df))]

    # Save the modified DataFrame to a new CSV file
    df.to_csv(output_csv, index=False)
    print(f"Processed CSV saved to {output_csv}")

# Example usage:
input_csv = "/content/drive/My Drive/texture_features_clean1.csv"
output_csv = "clean_output.csv"
process_csv(input_csv, output_csv)



from google.colab import files
files.download('clean_output.csv')

from google.colab import drive
  drive.mount('/content/drive')