# -*- coding: utf-8 -*-
"""Labeled_Features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6sE4dBwMucav1g68W2o7Ti8cuZFX1vA
"""

# 1. Mount your Google Drive
from google.colab import drive
drive.mount('/content/drive')  # you’ll be prompted to authenticate

# 2. Define the full path to your CSV in Drive
csv_path = '/content/drive/My Drive/project312/models/clean_color_features.csv'

# 3. Load into DataFrame
import pandas as pd
df = pd.read_csv(csv_path)

# 4. (Optional) see what labels you have before cleaning
print("Before cleaning:", df['Label'].unique())

# 5. Remove any '_<number>.png' suffix so labels are exactly 'Uninfected' or 'Parasitized'
df['Label'] = df['Label'].str.replace(r'(_\d+\.png)$', '', regex=True)

# 6. Map to numeric: Uninfected→0, Parasitized→1
df['Label'] = df['Label'].map({'Uninfected': 0, 'Parasitized': 1})

# 7. Verify the mapping
print("After mapping:", df['Label'].unique())
print(df.head())

# 8. Count how many 0’s and 1’s you have
counts = df['Label'].value_counts().sort_index()
print(f"Label counts:\n 0 (Uninfected): {counts.get(0,0)}\n 1 (Parasitized): {counts.get(1,0)}")

# 8. Save the cleaned CSV back to Drive (or locally if you prefer)
output_path = '/content/drive/My Drive/project312/models/dataRGB.csv'
df.to_csv(output_path, index=False)
print(f"Cleaned CSV written to {output_path}")